AWSTemplateFormatVersion: '2010-09-09'

Description: 
  This deploys an entry in Secrets Manager and exports it for use elsewhere.

Parameters:

  Username:
    Description: Enter the username.
    Type: String

  Password:
    Description: Enter the password.
    Type: String

  Service:
    Description: Enter the name of the service associated with this username and password.
    Type: String

Resources:

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Username and Password
      Name: 
        !Sub 
          - "${AWS::StackName}-${Service}"
          - {Service: !Ref Service}
      SecretString: !Sub '{"username": "${Username}", "password": "${Password}"}'
      Tags:
        - 
          Key: "Name"
          Value: 
            !Sub 
              - "${AWS::StackName}-${Service}"
              - {Service: !Ref Service}

Outputs:

  SecretOutput:
    Description: Docker Username and Password
    Export:
      Name:
        !Sub 
          - "${AWS::StackName}-${Service}"
          - {Service: !Ref Service}
    Value:
      Ref: Secret