AWSTemplateFormatVersion: '2010-09-09'

Description: 
  This template deploys an entry in Secrets Manager.

Parameters:

  Username:
    Description: Enter the username.
    Type: String

  Password:
    Description: Enter the password.
    Type: String

  Service:
    Description: Enter the name of the service associated with this username and password.
    Type: String

Resources:

  #Create the secret in Secrets Manager to be used by other AWS resources.
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Username and Password
      Name: 
        !Sub 
          - "${AWS::StackName}-${Service}"
          - {Service: !Ref Service}
      SecretString: !Sub '{"username": "${Username}", "password": "${Password}"}'
      Tags:
        - 
          Key: "Name"
          Value: 
            !Sub 
              - "${AWS::StackName}-${Service}"
              - {Service: !Ref Service}